default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: double-quote-string-fixer
      - id: check-yaml
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/csachs/pyproject-flake8
    rev: v5.0.4a1.post1
    hooks:
      - id: pyproject-flake8
        name: flake8
        description: 'A monkey patching wrapper to connect flake8 with pyproject.toml configuration'
        entry: pflake8
        language: python
        types: [ python ]
        require_serial: true
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: ['-iii', '-ll']
