# Generated by Django 4.1.1 on 2022-09-19 01:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalcategory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='goalcategory',
            name='updated',
            field=models.DateTimeField(
                auto_now=True, verbose_name='Дата последнего обновления'
            ),
        ),
        migrations.AlterUniqueTogether(
            name='goalcategory',
            unique_together={('user', 'title')},
        ),
    ]
