# Generated by Django 4.1.1 on 2022-09-19 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_alter_goalcategory_created_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='goalcategory',
            unique_together=set(),
        ),
    ]
